default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sslmode: require

development:
  <<: *default
  username: doadmin
  password: AVNS_e7siKw4mKEKCbz-zk5s
  host: db-postgresql-nyc3-22801-do-user-15310791-0.c.db.ondigitalocean.com
  port: 25060
  database: defaultdb

