default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Postgre2005
  host: localhost

development:
  <<: *default
  database: oficinaMecanica_development

test:
  <<: *default
  database: oficinaMecanica_test
